apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260521-224652-dhlma5brj9fi-service
spec:
  selector:
    app: enterprise-system-20260521-224652-dhlma5brj9fi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
